# Generated by Django 6.0.1 on 2026-01-27 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_breed', models.CharField(max_length=100)),
                ('pet_weight_lbs', models.PositiveIntegerField()),
                ('pet_age_years', models.PositiveIntegerField()),
                ('availability_notes', models.TextField()),
                ('grooming_frequency', models.CharField(max_length=100)),
                ('special_needs', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('confirmed', 'Confirmed'), ('completed', 'Completed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking_app.client')),
                ('services', models.ManyToManyField(to='booking_app.service')),
            ],
        ),
    ]
