# Generated by Django 6.0.1 on 2026-01-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0003_bookingrequest_scheduled_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewClientApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=30)),
                ('pet_name', models.CharField(max_length=80)),
                ('pet_breed', models.CharField(max_length=120)),
                ('pet_weight_lbs', models.PositiveIntegerField(blank=True, null=True)),
                ('pet_age_years', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
