# Generated by Django 6.0.1 on 2026-01-29 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0004_newclientapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='newclientapplication',
            name='zip_code',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
