# Generated by Django 6.0.1 on 2026-01-30 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0005_newclientapplication_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='availability_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='grooming_frequency',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
