# Generated by Django 6.0.1 on 2026-01-30 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0006_alter_bookingrequest_availability_notes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='availability_notes',
        ),
        migrations.RemoveField(
            model_name='bookingrequest',
            name='grooming_frequency',
        ),
    ]
