# Generated by Django 6.0.1 on 2026-01-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0007_remove_bookingrequest_availability_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingrequest',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
