# Generated by Django 6.0.1 on 2026-02-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0008_bookingrequest_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='address',
            field=models.CharField(max_length=255),
        ),
    ]
