# Generated by Django 6.0.1 on 2026-02-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0011_bookingrequest_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='newclientapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
