# Generated by Django 5.1.2 on 2026-02-24 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking_app', '0012_client_email_newclientapplication_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='approval_token',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
